### ISSUE TITLE
ablkit.reasoning.PrologKB crashed when using SWI-Prolog 64 bits, version 9.2+

### ISSUE THREAD

**Issue by LiuBodan** [AbductiveLearning/ABLkit#9]
Hi,

ablkit.reasoning.PrologKB will crash when using SWI-Prolog 64 bits, version 9.2.0 or above.
It works fine when using SWI-Prolog 9.1

thanks,
Bodan

**Comment by troyyyyy** [comment]
Hi Bodan,

Thank you for bringing this issue to our attention. Currently, the SWI-Prolog related components in ABLkit are integrated using [PySwip](https://github.com/yuce/pyswip). Unfortunately, it seems that PySwip has not yet been updated to accommodate changes in SWI-Prolog version 9.2.0 and above. For now, we can only recommend downgrading SWI-Prolog to version 8.2-9.1 to use with PrologKB in ABLkit.

I hope this answers your query. Also, in the future we may plan to adjust this and add support for SWI-Prolog version 9.2+. We appreciate your patience and understanding as we work on this.

Best regards.
